# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60c609c6221ae3b70607004ae6a3cb33"
name = "Sudae"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "sudae-3d-builder"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "https://your-app-url.com/apps/proxy"
subpath = "sudae-proxy"
prefix = "apps"

[pos]
embedded = false
